- name: Install required libraries for paru
  become: true
  pacman:
    name:
      - base-devel
    state: present
    update_cache: yes

- name: Download paru repository
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: "{{ lookup('env', 'HOME') }}/paru"

- name: Install paru
  shell: makepkg -si --noconfirm
  args:
    chdir: "{{ lookup('env', 'HOME') }}/paru"

- name: Remove paru repository
  shell: rm -rf ~/paru
